Traceback (most recent call last):
  File "/Users/aet/mambaforge/envs/codeforecon/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/aet/mambaforge/envs/codeforecon/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aet/mambaforge/envs/codeforecon/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/aet/mambaforge/envs/codeforecon/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/aet/mambaforge/envs/codeforecon/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/aet/mambaforge/envs/codeforecon/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/aet/mambaforge/envs/codeforecon/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
a = np.random.randint(9, size=(3, 3), dtype='int')
b = a @ np.linalg.inv(a)
b
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mLinAlgError[0m                               Traceback (most recent call last)
Cell [0;32mIn[18], line 2[0m
[1;32m      1[0m a [38;5;241m=[39m np[38;5;241m.[39mrandom[38;5;241m.[39mrandint([38;5;241m9[39m, size[38;5;241m=[39m([38;5;241m3[39m, [38;5;241m3[39m), dtype[38;5;241m=[39m[38;5;124m'[39m[38;5;124mint[39m[38;5;124m'[39m)
[0;32m----> 2[0m b [38;5;241m=[39m a [38;5;241m@[39m [43mnp[49m[38;5;241;43m.[39;49m[43mlinalg[49m[38;5;241;43m.[39;49m[43minv[49m[43m([49m[43ma[49m[43m)[49m
[1;32m      3[0m b

File [0;32m<__array_function__ internals>:200[0m, in [0;36minv[0;34m(*args, **kwargs)[0m

File [0;32m~/mambaforge/envs/codeforecon/lib/python3.10/site-packages/numpy/linalg/linalg.py:538[0m, in [0;36minv[0;34m(a)[0m
[1;32m    536[0m signature [38;5;241m=[39m [38;5;124m'[39m[38;5;124mD->D[39m[38;5;124m'[39m [38;5;28;01mif[39;00m isComplexType(t) [38;5;28;01melse[39;00m [38;5;124m'[39m[38;5;124md->d[39m[38;5;124m'[39m
[1;32m    537[0m extobj [38;5;241m=[39m get_linalg_error_extobj(_raise_linalgerror_singular)
[0;32m--> 538[0m ainv [38;5;241m=[39m [43m_umath_linalg[49m[38;5;241;43m.[39;49m[43minv[49m[43m([49m[43ma[49m[43m,[49m[43m [49m[43msignature[49m[38;5;241;43m=[39;49m[43msignature[49m[43m,[49m[43m [49m[43mextobj[49m[38;5;241;43m=[39;49m[43mextobj[49m[43m)[49m
[1;32m    539[0m [38;5;28;01mreturn[39;00m wrap(ainv[38;5;241m.[39mastype(result_t, copy[38;5;241m=[39m[38;5;28;01mFalse[39;00m))

File [0;32m~/mambaforge/envs/codeforecon/lib/python3.10/site-packages/numpy/linalg/linalg.py:89[0m, in [0;36m_raise_linalgerror_singular[0;34m(err, flag)[0m
[1;32m     88[0m [38;5;28;01mdef[39;00m [38;5;21m_raise_linalgerror_singular[39m(err, flag):
[0;32m---> 89[0m     [38;5;28;01mraise[39;00m LinAlgError([38;5;124m"[39m[38;5;124mSingular matrix[39m[38;5;124m"[39m)

[0;31mLinAlgError[0m: Singular matrix

